include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    invalid_annotation_target: error
    invalid_use_of_protected_member: error
    always_use_package_imports: error
    avoid_empty_else: error
    avoid_relative_lib_imports: error
    cancel_subscriptions: error
    close_sinks: error
    invariant_booleans: error
    no_duplicate_case_values: error
    throw_in_finally: error
#    always_declare_return_types: warning
#    always_put_required_named_parameters_first: warning
    annotate_overrides: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
#    avoid_unnecessary_containers: warning
#    directives_ordering: warning
#    empty_catches: warning
#    empty_constructor_bodies: warning
    only_throw_errors: error
#    prefer_final_fields: warning
#    prefer_final_in_for_each: warning
#    prefer_final_locals: warning
#    prefer_if_null_operators: warning
#    prefer_initializing_formals: warning
#    prefer_is_empty: warning
#    prefer_is_not_empty: warning
#    prefer_is_not_operator: warning
#    prefer_iterable_whereType: warning
#    prefer_mixin: warning
#    prefer_null_aware_method_calls: warning
#    prefer_null_aware_operators: warning
    recursive_getters: error
#    require_trailing_commas: warning
#    sized_box_for_whitespace: warning
#    sized_box_shrink_expand: warning
#    sort_child_properties_last: warning
#    sort_constructors_first: warning
#    sort_unnamed_constructors_first: warning
#    type_annotate_public_apis: warning
#    unawaited_futures: warning
#    use_colored_box: warning
#    use_decorated_box: warning
#    use_enums: warning
#    use_is_even_rather_than_modulo: warning
#    use_named_constants: warning
#    use_super_parameters: warning

  exclude:
    - test/
    - test/**.*
    - test_driver/
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
    - packages/
    - ui_kit/
    - plugin/
linter:
  rules:
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - cancel_subscriptions
    - close_sinks
    - empty_catches
    - always_use_package_imports
    - avoid_empty_else
    - avoid_relative_lib_imports
    - invariant_booleans
    - no_duplicate_case_values
    - throw_in_finally
    - use_build_context_synchronously
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - constant_identifier_names
    - directives_ordering
    - empty_constructor_bodies
#    - lines_longer_than_80_chars
    - only_throw_errors
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - recursive_getters
#    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_child_properties_last
#    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_super_parameters
